In [3]:
import polars as pl
import pandas as pd

In [58]:
#.loc[[627, 464, 600, 389, 603, 667, 180, 341, 704, 105, 502, 65, 324, 20]]
data = pd.read_csv('/Users/gabehope/Downloads/app_data.csv')[['Age', 'Appendix_Diameter', 'Migratory_Pain',  'RBC_Count', 'RBC_in_Urine', 'Peritonitis' ]].dropna().loc[[627, 464, 600, 217, 187, 185, 389, 603, 667, 180, 341, 704, 105, 502, 65, 324, 20]].sample(frac=1).reset_index()[['Age', 'Appendix_Diameter', 'Migratory_Pain',  'RBC_Count', 'RBC_in_Urine', 'Peritonitis']].replace(
    'no appendicitis', 'healthy'
    ).replace(
    '+', 'low'
    ).replace(
    '++', 'medium'
    ).replace(
    '+++', 'high'
    )#.to_csv('app_all.csv')

data['RBC_in_Urine'] = data['RBC_in_Urine'].replace(
    'no', 'none'
    )
data.to_csv('app_all.csv')

In [46]:
pd.read_csv('/Users/gabehope/Downloads/app_data.csv')

Age    BMI     Sex  Height  Weight  Length_of_Stay          Management  \
0    12.68  16.90  female   148.0    37.0             3.0        conservative   
1    14.10  31.90    male   147.0    69.5             2.0        conservative   
2    14.14  23.30  female   163.0    62.0             4.0        conservative   
3    16.37  20.60  female   165.0    56.0             3.0        conservative   
4    11.08  16.90  female   163.0    45.0             3.0        conservative   
..     ...    ...     ...     ...     ...             ...                 ...   
777  12.41  25.25  female   166.5    70.0             4.0    primary surgical   
778  17.09  20.43  female   158.0    51.0             6.0  secondary surgical   
779  14.99  19.91  female   152.0    46.0             4.0    primary surgical   
780   7.20  14.30    male   129.3    23.9             5.0    primary surgical   
781  11.51  18.17    male   146.5    39.0             4.0    primary surgical   

          Severity Diagnosis_Presumptive        Diagnosis  ...  Unnamed: 59  \
0    uncomplicated          appendicitis     appendicitis  ...          NaN   
1    uncomplicated          appendicitis  no appendicitis  ...          NaN   
2    uncomplicated          appendicitis  no appendicitis  ...          NaN   
3    uncomplicated          appendicitis  no appendicitis  ...          NaN   
4    uncomplicated          appendicitis     appendicitis  ...          NaN   
..             ...                   ...              ...  ...          ...   
777  uncomplicated          appendicitis     appendicitis  ...          NaN   
778    complicated          appendicitis     appendicitis  ...          NaN   
779  uncomplicated          appendicitis     appendicitis  ...          NaN   
780  uncomplicated          appendicitis     appendicitis  ...          NaN   
781  uncomplicated          appendicitis     appendicitis  ...          NaN   

     Unnamed: 60 Unnamed: 61  Unnamed: 62 Unnamed: 63 Unnamed: 64 Unnamed: 65  \
0            NaN         NaN          NaN         NaN         NaN         NaN   
1            NaN         NaN          NaN         NaN         NaN         NaN   
2            NaN         NaN          NaN         NaN         NaN         NaN   
3            NaN         NaN          NaN         NaN         NaN         NaN   
4            NaN         NaN          NaN         NaN         NaN         NaN   
..           ...         ...          ...         ...         ...         ...   
777          NaN         NaN          NaN         NaN         NaN         NaN   
778          NaN         NaN          NaN         NaN         NaN         NaN   
779          NaN         NaN          NaN         NaN         NaN         NaN   
780          NaN         NaN          NaN         NaN         NaN         NaN   
781          NaN         NaN          NaN         NaN         NaN         NaN   

    Unnamed: 66 Unnamed: 67 Unnamed: 68  
0           NaN         NaN         NaN  
1           NaN         NaN         NaN  
2           NaN         NaN         NaN  
3           NaN         NaN         NaN  
4           NaN         NaN         NaN  
..          ...         ...         ...  
777         NaN         NaN         NaN  
778         NaN         NaN         NaN  
779         NaN         NaN         NaN  
780         NaN         NaN         NaN  
781         NaN         NaN         NaN  

[782 rows x 69 columns]

In [45]:
ndata = pd.read_csv('/Users/gabehope/Downloads/app_data.csv')[['Age', 'Appendix_Diameter', 'Height', 'Weight',  'RBC_Count', 'Body_Temperature', 'WBC_Count', ]].dropna().loc[[627, 464, 600, 217, 187, 185, 389, 603, 667, 180, 341, 704, 105, 502, 65, 324, 20]].sample(frac=1).reset_index()[['Age', 'Appendix_Diameter', 'Height', 'Weight',  'RBC_Count', 'Body_Temperature', 'WBC_Count', ]].to_csv('app_numeric.csv')

In [59]:
ndata = pd.read_csv('app_numeric.csv')

In [61]:
del ndata['Unnamed: 0']

In [65]:
ndata.values

import numpy as np

def matrix_to_latex(matrix):
    """Converts a NumPy matrix to LaTeX."""

    latex_str = "\\begin{pmatrix}\n"
    for row in matrix:
        latex_str += " & ".join(map(str, row)) + "\\\\\n"
    latex_str += "\\end{pmatrix}"
    return latex_str

print(matrix_to_latex(ndata.values))

\begin{pmatrix}
16.66 & 9.0 & 174.0 & 65.0 & 5.31 & 36.6 & 6.6\\
10.74 & 9.0 & 146.0 & 57.5 & 5.66 & 37.3 & 10.2\\
9.04 & 5.3 & 134.0 & 29.4 & 4.92 & 36.0 & 5.1\\
10.75 & 5.0 & 155.0 & 54.5 & 4.79 & 37.7 & 10.3\\
7.3 & 6.2 & 123.0 & 23.5 & 4.64 & 37.4 & 21.1\\
5.11 & 7.0 & 116.0 & 22.0 & 4.55 & 40.2 & 19.4\\
14.36 & 9.0 & 163.0 & 50.0 & 4.84 & 37.5 & 14.3\\
9.61 & 9.0 & 140.0 & 29.2 & 5.18 & 38.7 & 14.3\\
15.83 & 12.0 & 153.0 & 59.0 & 4.33 & 36.7 & 12.8\\
9.58 & 7.0 & 132.0 & 24.7 & 5.04 & 38.4 & 13.5\\
10.37 & 5.5 & 156.0 & 39.0 & 4.8 & 37.4 & 5.6\\
14.52 & 4.5 & 181.0 & 55.0 & 4.9 & 37.0 & 9.0\\
12.41 & 3.7 & 150.5 & 42.5 & 5.49 & 37.2 & 9.1\\
6.67 & 3.5 & 124.0 & 38.5 & 5.27 & 39.6 & 16.8\\
15.21 & 8.5 & 155.0 & 85.0 & 4.62 & 36.8 & 12.4\\
12.43 & 12.0 & 157.0 & 46.0 & 4.62 & 37.1 & 16.4\\
10.51 & 9.0 & 134.5 & 27.0 & 5.03 & 37.4 & 12.8\\
\end{pmatrix}


$$\\begin{pmatrix}\n16.66 & 9.0 & 174.0 & 65.0 & 5.31 & 36.6 & 6.6\\\\\n10.74 & 9.0 & 146.0 & 57.5 & 5.66 & 37.3 & 10.2\\\\\n9.04 & 5.3 & 134.0 & 29.4 & 4.92 & 36.0 & 5.1\\\\\n10.75 & 5.0 & 155.0 & 54.5 & 4.79 & 37.7 & 10.3\\\\\n7.3 & 6.2 & 123.0 & 23.5 & 4.64 & 37.4 & 21.1\\\\\n5.11 & 7.0 & 116.0 & 22.0 & 4.55 & 40.2 & 19.4\\\\\n14.36 & 9.0 & 163.0 & 50.0 & 4.84 & 37.5 & 14.3\\\\\n9.61 & 9.0 & 140.0 & 29.2 & 5.18 & 38.7 & 14.3\\\\\n15.83 & 12.0 & 153.0 & 59.0 & 4.33 & 36.7 & 12.8\\\\\n9.58 & 7.0 & 132.0 & 24.7 & 5.04 & 38.4 & 13.5\\\\\n10.37 & 5.5 & 156.0 & 39.0 & 4.8 & 37.4 & 5.6\\\\\n14.52 & 4.5 & 181.0 & 55.0 & 4.9 & 37.0 & 9.0\\\\\n12.41 & 3.7 & 150.5 & 42.5 & 5.49 & 37.2 & 9.1\\\\\n6.67 & 3.5 & 124.0 & 38.5 & 5.27 & 39.6 & 16.8\\\\\n15.21 & 8.5 & 155.0 & 85.0 & 4.62 & 36.8 & 12.4\\\\\n12.43 & 12.0 & 157.0 & 46.0 & 4.62 & 37.1 & 16.4\\\\\n10.51 & 9.0 & 134.5 & 27.0 & 5.03 & 37.4 & 12.8\\\\\n\\end{pmatrix}$$

ndata

In [76]:
X = ndata.values

In [83]:
X[7]

array([  9.61,   9.  , 140.  ,  29.2 ,   5.18,  38.7 ,  14.3 ])

In [84]:
X[7].shape

(7,)

In [81]:
X[7][:, None]

[[  9.61]
 [  9.  ]
 [140.  ]
 [ 29.2 ]
 [  5.18]
 [ 38.7 ]
 [ 14.3 ]]


In [85]:
X[7][:, None].shape

(7, 1)

In [88]:
X[7][None, :]

array([[  9.61,   9.  , 140.  ,  29.2 ,   5.18,  38.7 ,  14.3 ]])

In [87]:
X[7][None, :].shape

(1, 7)

In [ ]:
from dataclasses import dataclass

@dataclass
class Patient:
    age: float
    pain: bool
    rbc_count: float
    rbc_urine: int
